iso_to_country = {
 'AD': 'Andorra',
 'AE': 'Vereinigte arabische Emirate',
 'AF': 'Afghanistan',
 'AG': 'Antigua und Barbuda',
 'AI': 'Anguilla',
 'AL': 'Albanien',
 'AM': 'Armenien',
 'AN': 'Niederländische Antillen',
 'AO': 'Angola',
 'AQ': 'Antarktis',
 'AR': 'Argentinien',
 'AS': 'Amerikanisch Samoa',
 'AT': 'Oesterreich',
 'AU': 'Australien',
 'AW': 'Aruba',
 'AZ': 'Aserbaidschan',
 'BA': 'Bosnien und Herzegowina',
 'BB': 'Barbados',
 'BD': 'Bangladesh',
 'BE': 'Belgien',
 'BF': 'Burkina Faso',
 'BG': 'Bulgarien',
 'BH': 'Bahrain',
 'BI': 'Burundi',
 'BJ': 'Benin',
 'BM': 'Bermuda (GB)',
 'BN': 'Brunei',
 'BO': 'Bolivien',
 'BR': 'Brasilien',
 'BS': 'Bahamas',
 'BT': 'Bhutan',
 'BV': 'Bouvet-Insel',
 'BW': 'Botswana',
 'BY': 'Belarus (Weissrussland)',
 'BZ': 'Belize',
 'CA': 'Kanada',
 'CC': 'Cocos-Inseln',
 'CF': 'Zentralafrikanische Republik',
 'CG': 'Kongo',
 'CH': 'Schweiz',
 'CI': 'Elfenbeinküste',
 'CK': 'Cook-Inseln',
 'CL': 'Chile',
 'CM': 'Kamerun',
 'CN': 'China (Volksrepublik)',
 'CO': 'Kolumbien',
 'CR': 'Costa Rica',
 'CU': 'Kuba',
 'CV': 'Kapverden',
 'CX': 'Christmas-Insel (AUS)',
 'CY': 'Zypern',
 'CZ': 'Tschechische Republik',
 'DE': 'Deutschland',
 'DJ': 'Djibouti',
 'DK': 'Dänemark',
 'DM': 'Dominica',
 'DO': 'Dominikanische Republik',
 'DZ': 'Algerien',
 'EC': 'Ecuador',
 'EE': 'Estland',
 'EG': 'Aegypten',
 'EH': 'Westsahara',
 'ER': 'Eritrea',
 'ES': 'Spanien',
 'ET': 'Aethiopien',
 'FI': 'Finnland',
 'FJ': 'Fidschi (Inseln)',
 'FK': 'Falkland-Inseln',
 'FM': 'Mikronesien',
 'FR': 'Frankreich',
 'GA': 'Gabun',
 'GB': 'Grossbritannien, Vereinigtes Königreich',
 'GD': 'Grenada',
 'GE': 'Georgien',
 'GF': 'Französisch-Guyana',
 'GH': 'Ghana',
 'GI': 'Gibraltar',
 'GL': 'Grönland',
 'GM': 'Gambia',
 'GN': 'Guinea',
 'GP': 'Guadeloupe',
 'GQ': 'Aequatorial-Guinea',
 'GR': 'Griechenland',
 'GT': 'Guatemala',
 'GU': 'Guam',
 'GW': 'Guinea-Bissau',
 'GY': 'Guyana (Republik)',
 'HK': 'Hongkong',
 'HM': 'Heard-, MacDonald-Inseln',
 'HN': 'Honduras',
 'HR': 'Kroatien',
 'HT': 'Haiti',
 'HU': 'Ungarn',
 'ID': 'Indonesien',
 'IE': 'Irland',
 'IL': 'Israel',
 'IN': 'Indien',
 'IO': 'Britische Territorien im indischen Ozean',
 'IQ': 'Irak',
 'IR': 'Iran',
 'IS': 'Island',
 'ISO': 'Land',
 'IT': 'Italien',
 'JM': 'Jamaika',
 'JO': 'Jordanien',
 'JP': 'Japan',
 'KE': 'Kenia',
 'KG': 'Kirgisistan',
 'KH': 'Kambodscha',
 'KI': 'Kiribati',
 'KM': 'Komoren',
 'KN': 'St. Kitts und Nevis',
 'KO': 'Kosovo',
 'KP': 'Korea (Nord)',
 'KR': 'Korea (Süd)',
 'KW': 'Kuwait',
 'KY': 'Kaiman-Inseln GB',
 'KZ': 'Kasachstan',
 'LA': 'Laos',
 'LB': 'Libanon',
 'LC': 'St. Lucia',
 'LI': 'Liechtenstein',
 'LK': 'Sri Lanka',
 'LR': 'Liberia',
 'LS': 'Lesotho',
 'LT': 'Litauen',
 'LU': 'Luxemburg',
 'LV': 'Lettland',
 'LY': 'Libyen',
 'MA': 'Marokko',
 'MC': 'Monaco',
 'MD': 'Moldau',
 'ME': 'Montenegro',
 'MG': 'Madagaskar',
 'MH': 'Marshall-Inseln',
 'MK': 'Mazedonien',
 'ML': 'Mali',
 'MM': 'Myanmar',
 'MN': 'Mongolei',
 'MO': 'Macao',
 'MQ': 'Martinique',
 'MR': 'Mauretanien',
 'MS': 'Montserrat',
 'MT': 'Malta',
 'MU': 'Mauritius',
 'MV': 'Malediven',
 'MW': 'Malawi',
 'MX': 'Mexiko',
 'MY': 'Malaysia',
 'MZ': 'Mosambik',
 'NA': 'Namibia',
 'NC': 'Neukaledonien',
 'NE': 'Niger',
 'NF': 'Norfolk-Insel',
 'NG': 'Nigeria',
 'NI': 'Nicaragua',
 'NL': 'Niederlande',
 'NO': 'Norwegen',
 'NP': 'Nepal',
 'NR': 'Nauru',
 'NU': 'Niue',
 'NZ': 'Neuseeland',
 'OM': 'Oman',
 'PA': 'Panama',
 'PE': 'Peru',
 'PF': 'Französisch-Polynesien',
 'PG': 'Papua-Neuguinea',
 'PH': 'Philippinen',
 'PK': 'Pakistan',
 'PL': 'Polen',
 'PM': 'St-Pierre und Miquelon',
 'PN': 'Pitcairn-Inseln',
 'PR': 'Puerto Rico',
 'PS': 'Palästina',
 'PT': 'Portugal',
 'PW': 'Palau',
 'PY': 'Paraguay',
 'QA': 'Katar',
 'RE': 'Reunion',
 'RO': 'Rumänien',
 'RS': 'Serbien',
 'RU': 'Russland',
 'RW': 'Rwanda',
 'SA': 'Saudi Arabien',
 'SB': 'Salomon Inseln',
 'SC': 'Seychellen',
 'SD': 'Sudan',
 'SE': 'Schweden',
 'SG': 'Singapur',
 'SH': 'St. Helena',
 'SI': 'Slowenien',
 'SJ': 'Svalbard und Jan Mayen',
 'SK': 'Slowakische Republik',
 'SL': 'Sierra Leone',
 'SM': 'San Marino',
 'SN': 'Senegal',
 'SO': 'Somalia',
 'SR': 'Suriname',
 'ST': 'São Tome und Principe',
 'SV': 'El Salvador',
 'SY': 'Syrien',
 'SZ': 'Swasiland',
 'TC': 'Turks-, Caicos-Inseln',
 'TD': 'Tschad',
 'TF': 'Südliches Eismeer (F)',
 'TG': 'Togo',
 'TH': 'Thailand',
 'TJ': 'Tadschikistan',
 'TK': 'Tokelau',
 'TM': 'Turkmenistan',
 'TN': 'Tunesien',
 'TO': 'Tonga',
 'TP': 'Timor-Leste',
 'TR': 'Türkei',
 'TT': 'Trinidad und Tobago',
 'TV': 'Tuvalu',
 'TW': 'Taiwan (China)',
 'TZ': 'Tansania',
 'UA': 'Ukraine',
 'UB': 'Officional of special organisation',
 'UG': 'Uganda',
 'UK': 'Unmik (Kosovo)',
 'UM': 'Treuhandinseln (USA)',
 'UN': 'Vereinte Nationen',
 'US': 'Vereinigte Staaten von Amerika (USA)',
 'UY': 'Uruguay',
 'UZ': 'Usbekistan',
 'VA': 'Vatikanstadt',
 'VC': 'St. Vincent und die Grenadinen',
 'VE': 'Venezuela',
 'VG': 'Jungfern-Inseln (UK)',
 'VI': 'Jungfern-Inseln (USA)',
 'VN': 'Vietnam',
 'VU': 'Vanuatu (Republik)',
 'WF': 'Wallis und Futuna',
 'WS': 'Samoa (West)',
 'X': 'unbekannt/inconnu/sconosciuto',
 'XP': 'INTERPOL',
 'XX': 'Staatenlos',
 'YE': 'Jemen',
 'YT': 'Mayotte (Insel)',
 'YU': 'Bundesrepublik Jugoslawien',
 'ZA': 'Südafrika',
 'ZM': 'Sambia',
 'ZR': 'Demokratische Republik Kongo',
 'ZW': 'Zimbabwe',
 'ZZ': 'Nation unbekannt (Personenfahndung)'
}
